apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: marsupial-go 
  janus-idp.io/tekton: marsupial-go
  backstage.io/kubernetes-id: marsupial-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: marsupial-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  