apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: marsupial-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: marsupial-go 
  name: marsupial-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: marsupial-go 
